-- ============================================================
-- Lumora Admin — Supabase / PostgreSQL
-- شغّل هذا الملف في Supabase → SQL Editor
-- ============================================================

create extension if not exists "pgcrypto";

-- ============ 1. جدول المنتجات ============
create table if not exists public.products (
  id bigint primary key generated by default as identity,
  cat text not null check (cat in ('tech','fashion','home','beauty','sport')),
  emoji text default '🛍️',
  hue int default 260 check (hue between 0 and 360),
  price numeric(10,2) not null check (price >= 0),
  old numeric(10,2) default 0 check (old >= 0),
  rating numeric(2,1) default 4.5 check (rating between 0 and 5),
  stock int default 0 check (stock >= 0),
  sold int default 0 check (sold >= 0),
  img text default '',
  name jsonb not null,
  description jsonb default '{}'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- ============ 2. جدول الطلبات ============
create table if not exists public.orders (
  id text primary key,
  customer_name text not null,
  phone text not null,
  city text not null,
  address text not null,
  notes text default '',
  items jsonb default '[]'::jsonb,
  total_amount numeric(10,2) not null,
  status text default 'pending'
    check (status in ('pending','confirmed','shipped','delivered','cancelled')),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- ============ 3. جدول الأدمن ============
create table if not exists public.admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  role text default 'admin' check (role in ('admin','super_admin','editor')),
  created_at timestamptz default now()
);

-- ============ 4. RLS ============
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.admins enable row level security;

create or replace function public.is_admin()
returns boolean language sql security definer stable as $$
  select exists (select 1 from public.admins where user_id = auth.uid());
$$;

drop policy if exists products_public_read on public.products;
create policy products_public_read on public.products
  for select using (true);

drop policy if exists products_admin_write on public.products;
create policy products_admin_write on public.products
  for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists orders_public_insert on public.orders;
create policy orders_public_insert on public.orders
  for insert with check (true);

drop policy if exists orders_admin_read on public.orders;
create policy orders_admin_read on public.orders
  for select to authenticated using (public.is_admin());

drop policy if exists orders_admin_update on public.orders;
create policy orders_admin_update on public.orders
  for update to authenticated using (public.is_admin());

drop policy if exists orders_admin_delete on public.orders;
create policy orders_admin_delete on public.orders
  for delete to authenticated using (public.is_admin());

drop policy if exists admins_self_read on public.admins;
create policy admins_self_read on public.admins
  for select to authenticated
  using (user_id = auth.uid() or exists (
    select 1 from public.admins a where a.user_id = auth.uid() and a.role = 'super_admin'
  ));

-- ============ 5. Triggers ============
create or replace function public.tg_set_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end $$;

drop trigger if exists products_updated_at on public.products;
create trigger products_updated_at before update on public.products
  for each row execute function public.tg_set_updated_at();

drop trigger if exists orders_updated_at on public.orders;
create trigger orders_updated_at before update on public.orders
  for each row execute function public.tg_set_updated_at();

-- ============ 6. إحصائيات ============
create or replace view public.admin_stats as
select
  (select count(*) from public.products) as total_products,
  (select count(*) from public.orders) as total_orders,
  (select count(*) from public.orders where status = 'pending') as pending_orders,
  (select coalesce(sum(total_amount),0) from public.orders where status != 'cancelled') as total_revenue,
  (select coalesce(sum(stock),0) from public.products) as total_stock,
  (select coalesce(sum(sold),0) from public.products) as total_sold,
  (select count(*) from public.products where stock = 0) as out_of_stock,
  (select count(*) from public.products where stock > 0 and stock <= 5) as low_stock;

grant select on public.admin_stats to authenticated;

-- ============ 7. بيانات تجريبية ============
insert into public.products (cat, emoji, hue, price, old, rating, stock, sold, name, description) values
('tech','🎧',258,89,119,4.8,12,320,
 '{"ar":"سماعات لاسلكية برو","fr":"Écouteurs Pro","en":"Pro Wireless Headphones"}',
 '{"ar":"عزل ضجيج وبطارية 30 ساعة","fr":"Réduction de bruit, 30h","en":"Noise cancelling, 30h"}'),
('tech','⌚',190,149,199,4.7,8,210,
 '{"ar":"ساعة ذكية ألترا","fr":"Montre Ultra","en":"Ultra Smart Watch"}',
 '{"ar":"تتبع صحي ورياضي","fr":"Suivi santé","en":"Health tracking"}')
on conflict do nothing;
